# Generated by Django 2.2.5 on 2019-09-04 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apart_name', models.CharField(max_length=20, verbose_name='股名')),
                ('note', models.TextField(verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, verbose_name='設備')),
                ('company_name', models.CharField(max_length=20, verbose_name='廠牌名')),
                ('product_type', models.CharField(max_length=20, verbose_name='類型')),
                ('product_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='產品預設帳號')),
                ('product_password', models.CharField(blank=True, max_length=20, null=True, verbose_name='產品預設密碼')),
                ('note', models.TextField(verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=20, verbose_name='站名')),
                ('station_number', models.CharField(max_length=20, verbose_name='車站編號')),
                ('station_ip_1', models.CharField(max_length=20, verbose_name='通訊所屬ip網段1')),
                ('station_ip_2', models.CharField(max_length=20, verbose_name='通訊所屬ip網段2')),
                ('station_ip_3', models.CharField(max_length=20, verbose_name='資訊所屬ip網段1')),
                ('note', models.TextField(verbose_name='備註')),
                ('apart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Apart')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=50, verbose_name='設備名稱')),
                ('ip', models.CharField(max_length=20, verbose_name='設備ip')),
                ('status', models.CharField(max_length=20, verbose_name='設備狀態')),
                ('setup_time', models.DateField(auto_now_add=True, verbose_name='安裝日期')),
                ('note', models.TextField(verbose_name='備註')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Product')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, verbose_name='員工編號')),
                ('employee_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(max_length=50, verbose_name='密碼')),
                ('note', models.TextField(verbose_name='備註')),
                ('apart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Apart')),
            ],
        ),
    ]
