# Generated by Django 2.2.5 on 2019-09-04 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apart',
            options={'verbose_name': '部門管理', 'verbose_name_plural': '部門管理'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '員工管理', 'verbose_name_plural': '員工管理'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '設備設定管理', 'verbose_name_plural': '設備設定管理'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '設備型號管理', 'verbose_name_plural': '設備型號管理'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': '捷運站管理', 'verbose_name_plural': '捷運站管理'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='apart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Apart', verbose_name='所屬部門'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Product', verbose_name='設備型號'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Station', verbose_name='所屬車站'),
        ),
        migrations.AlterField(
            model_name='station',
            name='apart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Apart', verbose_name='所屬部門'),
        ),
    ]
